services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/__tests__:/app/__tests__
    command: npm run test
    environment:
      - NODE_ENV=test
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server
    ports:
      - "9000:9000"
    volumes:
      - ./server/src:/app/src
      - ./server/__tests__:/app/__tests__
    command: npm run test
    environment:
      - NODE_ENV=test
      - CHOKIDAR_USEPOLLING=true
