services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client/src:/app/src
      - ./client/index.html:/app/index.html
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server
    ports:
      - "9000:9000"
    volumes:
      - ./server/src:/app/src
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
